language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: HKzget+JS4WZQWhUpCzJObqCYXxnr1NgjoCMVAOYRPJlyNrm8eYz7ZjNL0r9QjEGIWI5AKsZyAA2Bw8xek5BWRLP17MO8Zn+SBtgm6zuuFb6J4Q/AURoPKzb6Fu5MxD9eMQfTNWN4jnTMtLqC3lvbN4DIMwsuQPhn38vewZ3g0M=
  app: grg-foodtruckfinder
  on:
    repo: gregerg/foodtruckfinder
